### ISSUE TITLE
Tile color

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#11]
I think it would be nice if the tiles were slightly different shades of blue.  Maybe there could be 7 shades, and we make sure that no two adjacent tiles have the same color.

**Comment by nsmryan** [comment]
might try variations within a range.
potentially sandy color, but keep the blue palette
Vary to get differentiation, and potentially add to bitmap font.

**Comment by nsmryan** [comment]
This appears to be complete. Are you ready to close the issue, or is there something else to do with it?

**Comment by j0e1GMR** [comment]
I think we are in a good place with the tiles for now.

**Comment by nsmryan** [comment]
Okay, I'm going to close the issue. We can reopen another issue to continue the discussion.
