### ISSUE TITLE
Health Overdrew

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#117]
I died while surrounded by a gol and a pawn. My last action was to throw a stone, and I was attacked by both directly after. Although I died, my health bar is shown as full, and actually overflows the healthbar box. 

![image](https://user-images.githubusercontent.com/4422963/85210364-15756180-b2f4-11ea-9da5-5c6e5c491635.png)

**Comment by j0e1GMR** [comment]
This issue does seem reproducible, as long as you die on the turn that you throw a stone.

**Comment by nsmryan** [comment]
Fixed- health was becoming negative and causing a large health bar
