### ISSUE TITLE
Edge/corner pieces

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#12]
One of my original concepts for this game was to have walls that don't just exist in the middle of squares, but which can be in the middle, corner, or along edges. Michael Brough does this in Imbroglio, and I think that it is very interesting.  Unfortunately, it would be hard to represent in an ascii game.

**Comment by nsmryan** [comment]
I believe this can be closed- do you argee?

**Comment by j0e1GMR** [comment]
Yea I think so.
