### ISSUE TITLE
Enemy movement visualization overlay

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#23]
When you have your mouse over an enemy, the info about where they can move displays on top of, and replaces, the player @.  It also overlays on top of walls.

**Comment by nsmryan** [comment]
This issue is closed with 1d207b61dd029d6375e4744dac7fe2ff4daa60df which only draws markers on squares which have an unblocked line from the enemy to the marked square
This means that the player square, which is blocked, does not get a marker.
