### ISSUE TITLE
God Mode

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#24]
Makes you invincible, maybe other things

**Comment by nsmryan** [comment]
Currently pressing 't' provides a huge amount of hp, but does not give any other bonus.

Pressing 'v' shows the full map, although only making it searched, not showing all tiles as in fov.

Maybe pressing 't' should make fov cover the whole map for debugging.

**Comment by nsmryan** [comment]
All tiles are now visible in god mode.
The player has to move one tile before they become visible.
Currently this also sets all tiles to be walkable, although this is not used in the game.

Closed in a4046f63a1994e0bc2347e5151d59666837ca02e
