### ISSUE TITLE
Implement Palette 

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#30]
change names in the config file from color_orc to color_orange, as per the predefined game palette.

**Comment by nsmryan** [comment]
Do you think this is something you want to handle?
I could do the mechanical part of changing the config file, but I'm not sure what colors to use, and I'm not sure how we want to assign colors.

**Comment by j0e1GMR** [comment]
Yea, I think I should go ahead and do this one.  I've assigned it to myself.

**Comment by j0e1GMR** [comment]
Colors have been redone, except in cases where tcod colors were used, which has been left in for now.  These should also be replaced at some point.
