### ISSUE TITLE
arbitrary characters counting as walls

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#57]
![image](https://user-images.githubusercontent.com/4422963/75653162-ceaf0f00-5c11-11ea-955f-f6a06fbca4c0.png)

Certain tiles don't count as walls when placed in the terrain layer.  Most do, but oddly, both of the tree tiles do not get recognized.

**Comment by nsmryan** [comment]
This is probably just related to setting the blocked variable in the default case in the terrain layer, but I will check it out.

**Comment by nsmryan** [comment]
I made a change for this. Does it work and we can close this?
