### ISSUE TITLE
Pushing over columns

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#58]
The idea is that there is a column terrain piece, which can be pushed over by the player. When pushed, the columns falls onto the adjacent tile, destroying any monster in that tile and causing noise.

**Comment by nsmryan** [comment]
Try it out. The latest develop branch can push over columns and crush enemies behind them.
It does create a rubble tile, but  i didn't make that tile louder, which would be interesting.

**Comment by nsmryan** [comment]
The column push itself also make a noise, which would be a good idea.

**Comment by nsmryan** [comment]
Columns can pushed into walls.
