### ISSUE TITLE
Fog of War

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#80]
Tiles that you have never seen should be pure black. Tiles that you have seen in the past, but can't currently see, should show up dark. They should look exactly the way that tiles look currently that you have never seen.

**Comment by nsmryan** [comment]
I believe this concept is implemented. Try it out sometime.

**Comment by nsmryan** [comment]
Try this out again some time. This should be completed, and the config file has an entry called explored_alpha which controls the alpha of files that are explored but not visible.
