### ISSUE TITLE
Inventory management

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#90]
The player should be able to pick up two items at a time, and have one of these items be "active." Similar to the Binding of Isaac, where you can switch between two consumables. The switch can be done using Tab.

In addition to the two items, the player can have as many stones in their inventory as they want.

**Comment by nsmryan** [comment]
What about if you pick up an item with two in your inventory- what should happen?

This does sound good overall though.

**Comment by j0e1GMR** [comment]
I would say that if you have two items in your inventory and we have a system where one item is active at a time, then if you try to pick up another item it will replace your current active item which you will drop.

**Comment by nsmryan** [comment]
2 items max
1 active item
tab switches item
stones separate, as many as you want
d drops main item

**Comment by nsmryan** [comment]
Master has this change- check it out.

There are no rendering changes yet to star the primary item or anything with stones.

**Comment by nsmryan** [comment]
There is a '<' to note which is the active item
