### ISSUE TITLE
Push monsters two tiles when running

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#91]
If the player is adjacent to a monster, they are in the running state, and they move towards the monster, they should push the monster back two tiles.

**Comment by nsmryan** [comment]
This should work now.

Currently it only emits a sound at the final location, not the intermediate location. I think this is preferable, but I thought i would ask before closing the issue.

**Comment by j0e1GMR** [comment]
I feel like sound at the time location is good.
