### ISSUE TITLE
Crash while pushing while running

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#92]
In some cases, running into enemies, when it results in pushing them into a wall, causes the game to crash. 

The easiest way that I have found to replicate this is to sneak over to the right side of the map, and then sneak up to be adjacent on the left side of the elf. Then switch to running and run into the elf, the game will crash.

**Comment by nsmryan** [comment]
Try this again- i believe it is fixed.

**Comment by nsmryan** [comment]
Closing this issue- if something like this happens again we should open a new one
