### ISSUE TITLE
Gol movement

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#93]
In some cases, monsters do not move in the expected way.

Sometimes Gols move towards the player, but do not appear to try to gain diagonals in order to attack. 

In other cases, for instance when the place is one tile down and three tiles left from the Gol, the Gol will sit where it is without moving if the player passes a turn. This also happens with elfs in some cases but I cannot get it to be consistent.

**Comment by nsmryan** [comment]
This should be fixed now, but give it a try and see if they act the way you expect
