### ISSUE TITLE
Player running passed walls

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#94]
If the player is next to a terrain feature, such as a wall, and moves passed the wall, either diagonally or vertically, in the running state, they will only move one tile. 

![image](https://user-images.githubusercontent.com/4422963/77874001-72cfaa00-7200-11ea-9b5a-08449434fad0.png)

**Comment by nsmryan** [comment]
This seems to work for me- either i'm not reproducing exactly, or i unintentionally fixed it?

**Comment by j0e1GMR** [comment]
unfortunately, this still happens to me, even when I do a git reset --hard. Perhaps we will have to take a look on screenshare.

**Comment by nsmryan** [comment]
I don't think this is actually due to walls- it seem to be tied to how many times you press the run key 'x'. Try it out, but that is what i'm seeing.

**Comment by nsmryan** [comment]
This is a bug introduced when adding the shield. It is fixed on master.
